### ISSUE TITLE
Folder with special character

### ISSUE THREAD

**Issue by Dam-Buty** [IrosTheBeggar/mStream#29]
I'm getting a bug when trying to navigate to a folder that starts with a special character (well, i think that's the cause, as other folders work fine)

![image](https://cloud.githubusercontent.com/assets/1461760/26545199/06358d54-4465-11e7-8c64-321a787f4c54.png)

**Comment by Dam-Buty** [comment]
Scratch that : 

- it was actually a file, and i didn't see that it was added to the current playlist
- the metadata 500 error is actually happening (apparently) every time i add a file to a playlist

**Comment by IrosTheBeggar** [comment]
I'm interested in looking into the DB errors.  

Can you tell me what OS you're using and whether you're using mStream Express or the code checked out from npm/github?  If you're using th checked out code, what version of node do you have installed?

I'll try to recreate the environment myself to see if I can solve the problem

**Comment by Dam-Buty** [comment]
I'm using mStream Express on a windows 10 machine.

Once thing to note is that, as multi-directory isn't available yet, i've added a whole network drive as my music directory. The first folders scanned don't contain MP3s but thousands of ROMs, and the DB doesn't scan well (if i click "Build the database" it still gets 0 files). Maybe that's part of the explanation?

**Comment by IrosTheBeggar** [comment]
That's really interesting.  I wonder if it actually has something to due with being a network drive.  I haven't done any testing on network drives yet, I'm going to have to start doing that.

What protocol are you using for your network drive?

**Comment by Dam-Buty** [comment]
It's a regular Samba share from a NAS to my Windows box. Everything works fine, except the database building. I can browse, listen to the MP3s, create playlists etc... with no issue.

**Comment by IrosTheBeggar** [comment]
@Dam-Buty 

I fixed a bug that might solve the DB issues.  Get the latest version from https://github.com/IrosTheBeggar/mStream/releases/tag/v3.0.7 and let me know if it works

**Comment by Dam-Buty** [comment]
Hi Paul!

I've tested the 0.4.3 release but it still doesn't work for me, the DB remains at 0 files. Is there any way to get a log from the server, to further document the issue?

On the other hand, i've found a bug that really occurs in folders with special characters, more specifically with the Pound Sign ("#"). I'll try and document it : 

![image](https://user-images.githubusercontent.com/1461760/27424604-e5fe2cc4-5735-11e7-9ff5-58427c0bb8c2.png)

When i click on a track in this folder, I first get the 500 error on the metadata request, as with **every track**. But then, i see a request is made to : 

`http://xx.xx.xx.xx:3666/a06d56a6-f16d-4063-9c84-5240f80d2d39/Musiques/++Alternative++/NINE%20INCH%20NAILS/1994%20-%20The%20Downward%20Spiral%202CD/CD%20`

Notice how the path is cut short where the # sign should be. The next request goes to an endpoint called 
`access-denied` and returns a non-standard 598 status code.

![image](https://user-images.githubusercontent.com/1461760/27424935-0cca3572-5737-11e7-81b9-b7b74e5be65e.png)

Cheers!

**Comment by IrosTheBeggar** [comment]
Good find on the # sign bug.  I'll get working on a fix to that shortly.

Currently mStream Express doesn't have any logging.  I was worried about accidently flooding the users HD with log files so I didn't put it in.  I'm going to be working on adding an optional logging feature to the v0.5 release

**Comment by kuriot** [comment]
Yes, just came to open an issue about special characters.

![spectacle m27759](https://user-images.githubusercontent.com/25008488/27913646-7dcb9a08-6269-11e7-8c1b-2c87ae2a5154.png)

**Comment by IrosTheBeggar** [comment]
@kuriot 

Thanks for reporting that.  I'm going to have to find a better font that supports special characters

**Comment by IrosTheBeggar** [comment]
@kuriot 

The latest version on master fixes the font problems

@Dam-Buty 

The latest version fixes the # sign bug

I might close this issue and reopen it under a new and clean ticket

**Comment by IrosTheBeggar** [comment]
The latest version of mStream should address all issues in this thread. v0.6 of mStream Express will ship soon with these changes.
